name: MooWeather
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  flutter_riverpod: ^2.5.1
  geolocator: ^11.0.0
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.3
  logger: ^2.6.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

# Logo konfigürasyonu
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#4A90E2"
  adaptive_icon_foreground: "assets/icons/app_icon.png"
